#!/bin/bash
set -e

DOCKER_IMG="ros-noetic-image"

if [[ $# -eq 0 ]] ; then
  echo "WARNING: No arguments provided, image ${DOCKER_IMG} will be created"
else 
  DOCKER_IMG=$1
fi

PROJECT_ROOT="$(cd "$(dirname "$0")"; cd ..; pwd)"

echo "----- Building Docker image from ${PROJECT_ROOT}/Dockerfile "
docker build -t ${DOCKER_IMG} ${PROJECT_ROOT}